--------------------------------------------------
-- Mir AI configuration file (generated by Mir AI Control Panel)
--------------------------------------------------
CIRCLE_ON_IDLE=1
FOLLOW_AT_ONCE=0
HELP_OWNER_1ST=true
KILL_YOUR_ENEMIES_1ST=false
LONG_RANGE_SHOOTER=false
-- MEUH Mode
ANTI_AFK_MODE=true
BOLTS_ON_CHASE_ST=true
HP_PERC_DANGER=0
HP_PERC_SAFE2ATK=0
OWNER_CLOSEDISTANCE=2
TOO_FAR_TARGET=14
SKILL_TIME_OUT=300
NO_MOVING_TARGETS=false
ADV_MOTION_CHECK=false

--------------------------------------------------
-- Alchemist automatic skills
--------------------------------------------------
-- Alche Auto Attacks: HP Range
AAA_MinHP=100
AAA_MaxHP=32000
-- Auto Cart Revolution (ACR_MinEnemies 0=disabled)
ACR = {}
ACR.MinSP=20
ACR.MinEnemies=1
-- Auto Single Target (weapon based) Skill
AST = {}
AST.SkillID=0
AST.MinSP=20
AST.Level=5
-- Auto Aid Potion
CAN_DETECT_NOPOT=true
AAP = {}
AAP.Mode=4
AAP.HP_Perc=65
AAP.Level=1

--------------------------------------------------
-- Homunculus Skills: minimun SP to activate
--------------------------------------------------
-- Amistr
AS_AMI_BULW = {}
AS_AMI_BULW.MinSP=40
AS_AMI_BULW.Level=0
AS_AMI_CAST = {}
AS_AMI_CAST.MinSP=10
AS_AMI_CAST.Level=0
-- Filir
AS_FIL_MOON = {}
AS_FIL_MOON.MinSP=20
AS_FIL_MOON.Level=0
AS_FIL_ACCL = {}
AS_FIL_ACCL.MinSP=70
AS_FIL_ACCL.Level=0
AS_FIL_FLTT = {}
AS_FIL_FLTT.MinSP=70
AS_FIL_FLTT.Level=1
-- Lif
AS_LIF_HEAL = {}
AS_LIF_HEAL.MinSP=40
AS_LIF_HEAL.Level=5
AS_LIF_ESCP = {}
AS_LIF_ESCP.MinSP=40
AS_LIF_ESCP.Level=5
AS_LIF_MENT = {}
AS_LIF_MENT.MinSP=100
AS_LIF_MENT.Level=3
-- Vanilmirth
AS_VAN_CAPR = {}
AS_VAN_CAPR.MinSP=30
AS_VAN_CAPR.Level=0
AS_VAN_BLES = {}
AS_VAN_BLES.MinSP=40
AS_VAN_BLES.Level=0

--------------------------------------------------
-- Tact list: behaviour for each monster
--------------------------------------------------
DEFAULT_BEHA = BEHA_attack
DEFAULT_WITH = WITH_slow_power
Tact = {}
-- Thor V01
Tact[1833] = {"Kasa", BEHA_attack_1st, WITH_full_power, 5, 0}
Tact[1831] = {"Salamander", BEHA_attack, WITH_full_power, 5, 0}
Tact[1829] = {"Sword Master", BEHA_react_1st, WITH_full_power, 5, 0}
Tact[1830] = {"Bow Master", BEHA_react, WITH_full_power, 5, 0}
Tact[1839] = {"Byorgue", BEHA_react, WITH_full_power, 5, 0}
Tact[1837] = {"Fire Imp", BEHA_react, WITH_full_power, 5, 0}
-- Mosco Dun 01
Tact[1881] = {"Les", BEHA_attack_1st, WITH_full_power, 5, 0}
Tact[1882] = {"Baba Yaga", BEHA_attack_1st, WITH_full_power, 5, 0}
Tact[1880] = {"Wood Goblin", BEHA_react, WITH_no_skill, 5, 0}
-- Mosk Dun 03
Tact[1882] = {"Baba Yaga", BEHA_react, WITH_full_power, 5, 0}
Tact[1883] = {"Uzhas", BEHA_react, WITH_full_power, 5, 0}
Tact[1884] = {"Mavka", BEHA_attack_1st, WITH_full_power, 5, 0}
-- Hill Wind
Tact[1680] = {"Hill wind", BEHA_attack_1st, WITH_full_power, 5, 0}
-- Orc Dungeon (lvl 50+ Settings)
Tact[1189] = {"Orc Archer", BEHA_react_1st, WITH_full_power, 5, 0}
Tact[1177] = {"Zenorc", BEHA_attack_1st, WITH_full_power, 5, 0}
Tact[1152] = {"Orc Skeleton", BEHA_react, WITH_one_skill, 5, 0}
Tact[1111] = {"Drainliar", BEHA_attack_weak, WITH_no_skill, 1, 0}
Tact[1042] = {"Steel Chonchon", BEHA_attack_last, WITH_one_skill, 1, 0}
-- Poring and Metaling fields
Tact[1368] = {"Geographer", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1118] = {"Flora", BEHA_coward, WITH_full_power, 5, 0}
Tact[1613] = {"Metaling", BEHA_react, WITH_one_skill, 5, 0}
Tact[1031] = {"Poporing", BEHA_attack, WITH_no_skill, 5, -1}
Tact[1242] = {"Marin", BEHA_react, WITH_no_skill, 5, 0}
Tact[1113] = {"Drops", BEHA_attack, WITH_no_skill, 5, -1}
Tact[1002] = {"Poring", BEHA_attack_last, WITH_no_skill, 5, -1}
-- Eggs
Tact[1008] = {"Pupa", BEHA_attack_last, WITH_no_skill, 5, 0}
Tact[1048] = {"Thief Bug Egg", BEHA_attack_last, WITH_no_skill, 5, 0}
Tact[1047] = {"Peco Peco Egg", BEHA_attack_last, WITH_no_skill, 5, 0}
Tact[1097] = {"Ant Egg", BEHA_attack_last, WITH_no_skill, 5, 0}
-- Summoned Plants
Tact[1555] = {"Sm. Parasite", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1575] = {"Sm. Flora", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1579] = {"Sm. Hydra", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1589] = {"Sm. Mandragora", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1590] = {"Sm. Geographer", BEHA_avoid, WITH_no_skill, 5, 0}
-- WoE Guardians
Tact[1285] = {"WoE Guardian 1", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1286] = {"WoE Guardian 2", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1287] = {"WoE Guardian 3", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1288] = {"WoE Guardian 4", BEHA_avoid, WITH_no_skill, 5, 0}
-- Plants and mushrooms
Tact[1078] = {"Red Plant", BEHA_attack_last, WITH_no_skill, 5, 0}
Tact[1079] = {"Blue Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1080] = {"Green Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1081] = {"Yellow Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1082] = {"White Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1083] = {"Shining Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1084] = {"Black Mushroom", BEHA_react, WITH_no_skill, 5, 0}
Tact[1085] = {"Red Mushroom", BEHA_react, WITH_no_skill, 5, 0}
-- End Tact
